config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :users, only: [:edit, :update, :show]
  resources :posts, only: [:show, :new, :create]
  resources :events, only: [:show, :new, :create, :edit, :update] do
    member do
      get :confirm
    end
  end
  resources :rooms, only: [:index, :new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    image.attached?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :title, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :rooms
  has_many :messages
  has_many :posts
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_beginning_of_week
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :set_event, only: [:confirm, :edit, :update]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to event_path(@event.user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @events = @user.events.includes(:user)
  end

  def confirm
  end

  def edit
    if @event.user == current_user
      render :edit
    else
      redirect_to root_path
    end
  end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event.user.id)
    else
      render :edit
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end

  private

  def set_beginning_of_week
    Date.beginning_of_week = :sunday
  end

  def event_params
    params.require(:event).permit(:title, :start_time, :finish_time, :contents).merge(user_id: current_user.id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :set_room, only: [:index, :create]

  def index
    @message = Message.new
    @messages = @room.messages.includes(:user)
  end

  def create
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  def set_room
    @rooms = Room.all
    @room = Room.find(params[:room_id])
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.includes(:user).order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post.user.id)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :image).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name, :info)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @messages = @user.messages
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/confirm.html.erb
<div class="event-header">
  <a class="title" href="#"><b>Schedule</b></a>
  <div class="lists">
    <li><%= link_to '戻る', :back, class: 'event'%></li>
    <% if user_signed_in? && current_user.id == @event.user.id %>
      <li><%= link_to '予定を編集', edit_event_path, class: 'event'%></li>
    <% end %>
  </div>
</div>

<div class="show-events">
  <div class="show-event">
    <h1>タイトル</h1>
    <div class="event-more"><%= @event.title %></div>
  </div>
  <div class="show-event">
    <h1>開始時間</h1>
    <div class="event-more"><%= l(@event.start_time, format: :long) %></div>
  </div>
  <div class="show-event">
    <h1>終了時間</h1>
    <div class="event-more"><%= l(@event.finish_time, format: :long) %></div>
  </div>
  <div class="show-event">
    <h1>内容</h1>
    <div class="event-more"><%= @event.contents %></div>
  </div>
</div>

app/views/events/edit.html.erb
<div class='event-form'>
  <h1>予定の編集</h1>
  <%= form_with model: @event, id: @event.id, local: true do |f|%>
    <div class='event-form_field'>
      <div class='event-form_field-left'>
        <%= f.label :タイトル, class: 'event-form_label'%>
      </div>
      <div class='event-form_field-right'>
        <%= f.text_field :title, class: 'event-name event-form_input'%>
      </div>
    </div>
    <div class='event-form_field'>
      <div class='event-form_field-left'>
        <%= f.label :開始時間, class: 'event-form_label'%>
      </div>
      <div class='event-form_field-right_time'>
        <%= f.datetime_select :start_time, class: 'event-time event-form_input'%>
      </div>
    </div>
    <div class='event-form_field'>
      <div class='event-form_field-left'>
        <%= f.label :終了時間, class: 'event-form_label'%>
      </div>
      <div class='event-form_field-right_time'>
        <%= f.datetime_select :finish_time, class: 'event-time event-form_input'%>
      </div>
    </div>
    <div class='event-form_field'>
      <div class='event-form_field-left'>
        <%= f.label :内容, class: 'event-form_label'%>
      </div>
      <div class='event-form_field-right'>
        <%= f.text_area :contents, class: 'event-contents event-form_input'%>
      </div>
    </div>
    <div class='event-form_field_edit_btn'>
      <%= f.submit :更新する, class: 'event-form_action-btn'%>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div class='event-form'>
  <h1>予定の登録</h1>
  <%= form_with model: @event, local: true do |f| %>
  <%= render 'devise/shared/error_messages', model: f.object %>

    <div class='event-form_field'>
      <div class='event-form_field-left'>
        <%= f.label :タイトル, class: 'event-form_label'%>
      </div>
      <div class='event-form_field-right'>
        <%= f.text_field :title, class: 'event-name event-form_input', placeholder: 'タイトルを入力してください'%>
      </div>
    </div>
    <div class='event-form_field'>
      <div class='event-form_field-left'>
        <%= f.label :開始時間, class: 'event-form_label'%>
      </div>
      <div class='event-form_field-right_time'>
        <%= f.datetime_select :start_time, class: 'event-time event-form_input'%>
      </div>
    </div>
    <div class='event-form_field'>
      <div class='event-form_field-left'>
        <%= f.label :終了時間, class: 'event-form_label'%>
      </div>
      <div class='event-form_field-right_time'>
        <%= f.datetime_select :finish_time, class: 'event-time event-form_input'%>
      </div>
    </div>
    <div class='event-form_field'>
      <div class='event-form_field-left'>
        <%= f.label :内容, class: 'event-form_label'%>
      </div>
      <div class='event-form_field-right'>
        <%= f.text_area :contents, class: 'event-contents event-form_input', placeholder: '内容を入力してください', rows:"7"%>
      </div>
    </div>
    <div class='event-form_field_btn'>
      <%= f.submit :登録する, class: 'event-form_action-btn'%>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="event-header">
  <a class="title" href="#"><b>Schedule</b></a>
  <div class="event-header">
    <form class ="search-form" action="#">
      <input class="input-box" placeholder="予定を探す">
      <button class="search-button">検索</button>
    </form>
  </div>
  <div class="lists">
    <li><%= link_to 'マイページへ戻る', user_path, class: 'event'%></li>
    <% if user_signed_in? && current_user.id == @user.id %>
      <li><%= link_to '予定を登録', new_event_path, class: 'event'%></li>
    <% end %>
  </div>
</div>

<div class="event-section">
  <%= month_calendar events: @events do |date, events| %>
    <%= date.day %>
    <% events.each do |event| %>
      <div class="event-info">
        <%= link_to event.title, confirm_event_path(event.id), class: 'trigger'%>
      </div>
    <% end %>
  <% end %>
</div>

<script>
  var trigger = document.getElementsByClassName("trigger");
  var triggers = Array.from(trigger);

    triggers.forEach(function(target) {

    target.addEventListener('mouseover', function() {
      target.setAttribute("style", "color:#F28379;");
    });

    target.addEventListener('mouseout', function() {
      target.setAttribute("style", "color:#737373;");
    });
  });
</script>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Favo Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <link rel="stylesheet" type="text/css" href="stylesheets/reset.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <a><%= link_to message.user.nickname, "/users/#{message.user.id}" %></a>
    </div>
    <div class="message-date">
      <%= l message.created_at, format: :long%>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= message.content %>
    </div>
    <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<% if user_signed_in? %>
  <div class="create-room">
    <%= link_to "チャットを作成", new_room_path %>
  </div>
<% end %>

<div class="rooms">
  <% @rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.name, room_messages_path(room) %>
      </div>
      <div class="room-info">
        <%= room.info %></a>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<header class="top-page-header">
  <%= render "rooms/top_header" %>
</header>
<div class="wrapper">
  <div class="side-bar">
    <%= render "messages/side_bar" %>
  </div>
  <div class="main-chat">
    <div class="messages">
      <div class="chat-header">
        <div class="room-name_header">
          <%= @room.name %>
        </div>
        <% if user_signed_in? %>
          <div class="finish-room">
            <%= link_to "チャット終了", room_path(@room), method: :delete %>
          </div>
        <% end %>
      </div>
      <%= render partial: 'message', collection: @messages %>
    </div>
    <%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
      <div class="form-input">
        <%= f.text_field :content, class: 'form-message', placeholder: 'メッセージを送信してください' %>
        <label class="form-image">
          <span class="image-file">画像</span>
          <%= f.file_field :image, class: 'hidden' %>
        </label>
      </div>
      <%= f.submit '送信', class: 'form-submit' %>
    <% end %>
  <div>   
</div>  

app/views/posts/new.html.erb
<div class='post-form'>
  <h1>新規投稿の作成</h1>
  <%=form_with model: @post, local: true do |f|%>
    <%= render 'devise/shared/error_messages', model: f.object %>

    <div class='post-form_field'>
      <div class='post-form_field-left'>
        <%= f.label :画像, class: 'post-form_label'%>
      </div>
      <div class='image-upload'>
        <p>画像をアップロード</p>
        <%= f.file_field :image, class: 'post-image post-form_input'%>
      </div>
    </div>
    <div class='post-form_field'>
      <div class='post-form_field-left'>
        <%= f.label :タイトル, class: 'post-form_label'%>
      </div>
      <div class='post-form_field-right'>
        <%= f.text_field :title, class: 'post-title post-form_input', placeholder: 'タイトルを入力してください'%>
      </div>
    </div>
    <div class='post-form_field'>
      <div class='post-form_field-left'>
        <%= f.label :詳細, class: 'post-form_label'%>
      </div>
      <div class='post-form_field-right'>
        <%= f.text_area :text, class: 'post-text post-form_input', placeholder: '詳細を入力してください',rows:"7"%>
      </div>
    </div>
    <div class='post-form_field'>
      <%= f.submit :新規投稿の作成, class: 'post-form_action-btn'%>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="mypage-header">
  <a class="title" href="#"><b>Favo Post</b></a>
  <div class="mypage-header">
    <form class ="search-form" action="#">
      <input class="input-box" placeholder="投稿を探す">
      <button class="search-button">検索</button>
    </form>
  </div>
  <div class="lists">
    <li><%= link_to 'マイページへ戻る', user_path, class: 'post' %></li>
    <% if user_signed_in? && current_user.id == @user.id %>
      <li><%= link_to 'POST', new_post_path, class: 'post'%></li>
    <% end %>
  </div>
</div>

<div class="post-row">
  <% @posts.each do |post| %>
    <div class="post-section">
      <div class="post-img-content">
        <%= image_tag post.image.variant(resize: '700x700'), class:"post-img" %>
      </div>
      <div class="post-content">
        <div class="post-title">
          <h1><%= post.title %></h1>
          <h3><%= l(post.created_at, format: :long) %></h3>
        </div>
        <div class="post-text">
          <p><%= post.text %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/_side_bar.html.erb
<div class="create-room">
  <%= link_to "チャットを作成", new_room_path %>
</div>

<div class="rooms">
  <% @rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <a href="#"><%= room.name %></a>
      </div>
      <div class="room-info">
        <%= room.info %></a>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/_top_header.html.erb
<div class="left-side-header">
  <a class="title" href="#"><b>Favo Chat</b></a>
</div>
<div class="right-side-header">
  <form class ="search-form" action="#">
    <input class="input-box" placeholder="チャットルームを探す">
    <button class="search-button">検索</button>
  </form>
  <div class ="user">
    <ul class="lists">
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, "/users/#{current_user.id}", class: "user-nickname"%></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/rooms/index.html.erb
<header class="top-page-header">
  <%= render "top_header" %>
</header>
<div class="wrapper">
  <div class="side-bar">
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルームの作成</h1>
  <%=form_with model: @room, local: true do |f|%>
    <%= render 'devise/shared/error_messages', model: f.object %>

    <div class='chat-room-form_field'>
      <div class='chat-room-form_field-left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form_label'%>
      </div>
      <div class='chat-room-form_field-right'>
        <%= f.text_field :name, class: 'chat-room-name chat-room-form_input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form_field'>
      <div class='chat-room-form_field-left'>
        <%= f.label :チャットルームの説明, class: 'chat-room-form_label'%>
      </div>
      <div class='chat-room-form_field-right'>
        <%= f.text_field :info, class: 'chat-room-info chat-room-form_input', placeholder: 'チャットルームの説明を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form_field'>
      <%= f.submit :チャットルームの作成, class: 'chat-room-form_action-btn'%>
    </div>
  <% end %>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page_innner clearfix'>
    <div class='account-page_inner-header account-page_header'>
      <div class='account-page_left'>
        <h2>EDIT ACCOUNT</h2>
        <h5>アカウントの編集</h5>
      </div>
      <div class='account-page_right'>
        <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: 'btn'%>
        <%= link_to "マイページへ戻る", :back, class: 'btn'%>
      </div>
    </div>
    <div class='account-page_inner-main user-form'>
      <%= form_with model:current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :nickname%>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "更新する", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="top-page-header-mypage">
  <a class="mypage-title" >
    <h2>MYPAGE</h2>
    <h5><%= @nickname %>さんのマイページ</h5>
  </a>
  <div class='account-page_right'>
    <%= link_to "チャットへ戻る", root_path, class: 'btn'%>
  </div>
</div>
<div class="mypage-content">
  <ul class="mypage-lists">
    <% if user_signed_in? && current_user.id == @user.id %>
      <li><%= link_to 'EDIT ACCOUNT', edit_user_path, class: "edit-account-page" %>
        <p>アカウントの編集</p>
      </li>
    <% end %>
    <li><%= link_to 'POSTS', post_path, class: "post-page" %>
      <p>投稿一覧</p>
    </li>
    <li><%= link_to 'CALENDAR', event_path(@user.id), class: "calendar-page" %>
      <p>カレンダー</p>
    </li>
  </ul>
</div>